USE vaxdb;

#1
SELECT P.SSN, P.NAME, SUM(T.COST), COUNT(DISTINCT U.STAY)
FROM PATIENT P, UNDERGOES U, TREATMENT T, STAY S
WHERE P.AGE>=30 AND P.AGE<=40 AND P.GENDER='MALE' AND P.SSN=U.PATIENT AND T.CODE=U.TREATMENT AND S.PATIENT=U.PATIENT 
GROUP BY P.SSN, P.NAME 
HAVING COUNT(DISTINCT STAY)>1
;
#2
SELECT N.EMPLOYEEID, N.NAME, COUNT(DISTINCT OC.BLOCKCODE)
FROM NURSE N, ON_CALL OC
WHERE OC.NURSE=N.EMPLOYEEID AND OC.ONCALLSTART>='2008-04-20 23:22:00' AND OC.ONCALLEND<='2009-06-04 11:00:00' AND OC.BLOCKFLOOR>=4 AND OC.BLOCKFLOOR<=7
GROUP BY N.EMPLOYEEID
HAVING COUNT(*)>1
;
#3!!!!
SELECT P.SSN, P.NAME
FROM PATIENT P, VACCINATION V
WHERE P.GENDER='FEMALE' AND P.AGE>40 AND P.SSN=V.PATIENT_SSN
GROUP BY V.PATIENT_SSN
;
#4
SELECT M.NAME, M.BRAND, COUNT(*) AS PATIENTS
FROM MEDICATION M, PRESCRIBES P
WHERE M.CODE=P.MEDICATION
GROUP BY M.CODE
HAVING COUNT(*)>1
;
#5
SELECT V1.PATIENT_SSN
FROM VACCINATION V1
WHERE NOT EXISTS
(SELECT V2.PATIENT_SSN FROM VACCINATION V2
WHERE V1.PATIENT_SSN=V2.PATIENT_SSN AND V1.PHYSICIAN_EMPLOYEEID<>V2.PHYSICIAN_EMPLOYEEID)
;
#6
SELECT 'YES' AS ANSWER
WHERE EXISTS 
(SELECT * FROM STAY S
WHERE S.STAYSTART>='2013-1-1' AND S.STAYEND<='2013-12-31')
UNION
SELECT 'NO' AS ANSWER
WHERE NOT EXISTS 
(SELECT * FROM STAY S
WHERE S.STAYSTART>='2013-1-1' AND S.STAYEND<='2013-12-31')
;
#7
SELECT PH.NAME, PH.POSITION, COUNT(*) AS NUMOFPATIENTS
FROM PHYSICIAN PH, UNDERGOES U
WHERE PH.POSITION='PATHOLOGY' AND PH.EMPLOYEEID=U.PHYSICIAN
GROUP BY PH.EMPLOYEEID
HAVING COUNT(*)
UNION
SELECT PH.NAME, PH.POSITION, 0
FROM PHYSICIAN PH
WHERE PH.POSITION='PATHOLOGY' AND NOT EXISTS 
(SELECT * FROM UNDERGOES U
WHERE PH.EMPLOYEEID=U.PHYSICIAN)
GROUP BY PH.EMPLOYEEID
;
#8
SELECT P.NAME
FROM PATIENT P
WHERE NOT EXISTS 
(SELECT * FROM VACCINATION V
WHERE P.SSN=V.PATIENT_SSN)
GROUP BY P.SSN
UNION
SELECT P.NAME
FROM PATIENT P, VACCINATION V
WHERE P.SSN=V.PATIENT_SSN
GROUP BY V.PATIENT_SSN
HAVING COUNT(*)=1
;
#9
SELECT V.VACCINES_VAX_NAME
FROM VACCINATION V
GROUP BY V.VACCINES_VAX_NAME
HAVING COUNT(*)>=ALL
(SELECT COUNT(*) FROM VACCINATION 
GROUP BY VACCINES_VAX_NAME)
;
#10!!!!
SELECT P.NAME, T.NAME, T.CODE, TI.SPECIALITY
FROM TREATMENT T, TRAINED_IN TI, PHYSICIAN P
WHERE TI.SPECIALITY=T.CODE AND T.NAME='RADIATION ONCOLOGY'
;