-- MySQL Script generated by MySQL Workbench
-- Thu Apr  1 23:52:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `HIN` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`HIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citizen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citizen` (
  `afm` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `e-mail` VARCHAR(45) NULL,
  `date_of_birth` DATETIME NULL,
  `age` INT NULL,
  PRIMARY KEY (`afm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctors` (
  `afm` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `speciality` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  `address` INT NULL,
  `hospital_HIN` INT NOT NULL,
  PRIMARY KEY (`afm`),
  INDEX `fk_doctors_hospital1_idx` (`hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_doctors_hospital1`
    FOREIGN KEY (`hospital_HIN`)
    REFERENCES `mydb`.`hospital` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`test` (
  `test_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ward` (
  `ward_id` VARCHAR(45) NOT NULL,
  `number_of_rooms` INT NOT NULL,
  `occupied` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  `is_meth` TINYINT NOT NULL,
  `is_covid` TINYINT NULL,
  `hospital_HIN` INT NOT NULL,
  `medical_speciality` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ward_id`, `hospital_HIN`),
  INDEX `fk_ward_hospital1_idx` (`hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_ward_hospital1`
    FOREIGN KEY (`hospital_HIN`)
    REFERENCES `mydb`.`hospital` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_number` INT NOT NULL,
  `number_of_beds` INT NULL,
  `ward_ward_id` VARCHAR(45) NOT NULL,
  `ward_hospital_HIN` INT NOT NULL,
  PRIMARY KEY (`room_number`, `ward_ward_id`, `ward_hospital_HIN`),
  INDEX `fk_room_ward1_idx` (`ward_ward_id` ASC, `ward_hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_room_ward1`
    FOREIGN KEY (`ward_ward_id` , `ward_hospital_HIN`)
    REFERENCES `mydb`.`ward` (`ward_id` , `hospital_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_in_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient_in_hospital` (
  `patient_history` INT NOT NULL,
  `citizen_afm` INT NOT NULL,
  `hospital_HIN` INT NOT NULL,
  PRIMARY KEY (`patient_history`, `citizen_afm`, `hospital_HIN`),
  INDEX `fk_patient_in_hospital_citizen1_idx` (`citizen_afm` ASC) VISIBLE,
  INDEX `fk_patient_in_hospital_hospital1_idx` (`hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_patient_in_hospital_citizen1`
    FOREIGN KEY (`citizen_afm`)
    REFERENCES `mydb`.`citizen` (`afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_in_hospital_hospital1`
    FOREIGN KEY (`hospital_HIN`)
    REFERENCES `mydb`.`hospital` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacts` (
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `examination_date` VARCHAR(45) NOT NULL,
  `phone_number` INT NULL,
  `patient_in_hospital_patient_history` INT NOT NULL,
  `patient_in_hospital_citizen_afm` INT NOT NULL,
  PRIMARY KEY (`name`, `patient_in_hospital_patient_history`, `patient_in_hospital_citizen_afm`),
  INDEX `fk_contacts_patient_in_hospital1_idx` (`patient_in_hospital_patient_history` ASC, `patient_in_hospital_citizen_afm` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_patient_in_hospital1`
    FOREIGN KEY (`patient_in_hospital_patient_history` , `patient_in_hospital_citizen_afm`)
    REFERENCES `mydb`.`patient_in_hospital` (`patient_history` , `citizen_afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diagnostics_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnostics_center` (
  `HIN` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`HIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical_exams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical_exams` (
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EOF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EOF` (
  `approval_code` INT NULL,
  `date_of_aproof` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`approval_code`, `date_of_aproof`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccines` (
  `EMA` INT NOT NULL,
  `number_of_doses` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `EOF_approval_code` INT NOT NULL,
  `EOF_date_of_aproof` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EMA`),
  INDEX `fk_vaccines_EOF1_idx` (`EOF_approval_code` ASC, `EOF_date_of_aproof` ASC) VISIBLE,
  CONSTRAINT `fk_vaccines_EOF1`
    FOREIGN KEY (`EOF_approval_code` , `EOF_date_of_aproof`)
    REFERENCES `mydb`.`EOF` (`approval_code` , `date_of_aproof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_production_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_production_companies` (
  `code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` INT NOT NULL,
  `e-mai` VARCHAR(45) NOT NULL,
  `technology_used` VARCHAR(45) NOT NULL,
  `storage_conditions` VARCHAR(45) NOT NULL,
  `average_quantity_per_month` INT NOT NULL,
  `vaccines_EMA` INT NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_vaccine_production_companies_vaccines1_idx` (`vaccines_EMA` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_production_companies_vaccines1`
    FOREIGN KEY (`vaccines_EMA`)
    REFERENCES `mydb`.`vaccines` (`EMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_centers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_centers` (
  `hospital_HIN` INT NOT NULL,
  `diagnostic_center_HIN` INT NOT NULL,
  `is_vaccine_center` TINYINT NOT NULL,
  PRIMARY KEY (`hospital_HIN`, `diagnostic_center_HIN`),
  INDEX `fk_hospital_has_diagnostic_center_diagnostic_center1_idx` (`diagnostic_center_HIN` ASC) VISIBLE,
  INDEX `fk_hospital_has_diagnostic_center_hospital1_idx` (`hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_has_diagnostic_center_hospital1`
    FOREIGN KEY (`hospital_HIN`)
    REFERENCES `mydb`.`hospital` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_has_diagnostic_center_diagnostic_center1`
    FOREIGN KEY (`diagnostic_center_HIN`)
    REFERENCES `mydb`.`diagnostics_center` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storage_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storage_companies` (
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `vaccine_production_companies_code` INT NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `fk_storage_companies_vaccine_production_companies_idx` (`vaccine_production_companies_code` ASC) VISIBLE,
  CONSTRAINT `fk_storage_companies_vaccine_production_companies`
    FOREIGN KEY (`vaccine_production_companies_code`)
    REFERENCES `mydb`.`vaccine_production_companies` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_batch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_batch` (
  `code` INT NOT NULL,
  `country_of_export` VARCHAR(45) NOT NULL,
  `date_produced` DATETIME NOT NULL,
  `quantity_of_vaccines` INT NOT NULL,
  `vaccine_production_companies_code` INT NOT NULL,
  `vaccine_centers_hospital_HIN` INT NOT NULL,
  `vaccine_centers_diagnostic_center_HIN` INT NOT NULL,
  `storage_companies_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`, `vaccine_production_companies_code`, `storage_companies_name`),
  INDEX `fk_vaccine_batch_vaccine_production_companies1_idx` (`vaccine_production_companies_code` ASC) VISIBLE,
  INDEX `fk_vaccine_batch_vaccine_centers1_idx` (`vaccine_centers_hospital_HIN` ASC, `vaccine_centers_diagnostic_center_HIN` ASC) VISIBLE,
  INDEX `fk_vaccine_batch_storage_companies1_idx` (`storage_companies_name` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_batch_vaccine_production_companies1`
    FOREIGN KEY (`vaccine_production_companies_code`)
    REFERENCES `mydb`.`vaccine_production_companies` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_batch_vaccine_centers1`
    FOREIGN KEY (`vaccine_centers_hospital_HIN` , `vaccine_centers_diagnostic_center_HIN`)
    REFERENCES `mydb`.`vaccine_centers` (`hospital_HIN` , `diagnostic_center_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_batch_storage_companies1`
    FOREIGN KEY (`storage_companies_name`)
    REFERENCES `mydb`.`storage_companies` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HDIKA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HDIKA` (
  `AMKA` INT NOT NULL,
  `citizen_afm` INT NOT NULL,
  PRIMARY KEY (`AMKA`),
  INDEX `fk_HDIKA_citizen1_idx` (`citizen_afm` ASC) VISIBLE,
  CONSTRAINT `fk_HDIKA_citizen1`
    FOREIGN KEY (`citizen_afm`)
    REFERENCES `mydb`.`citizen` (`afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_in_diagnostics_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient_in_diagnostics_center` (
  `patient_history` INT NOT NULL,
  `citizen_afm` INT NOT NULL,
  `diagnostics_center_HIN` INT NOT NULL,
  PRIMARY KEY (`patient_history`, `citizen_afm`, `diagnostics_center_HIN`),
  INDEX `fk_patient_in_diagnostics_center_citizen1_idx` (`citizen_afm` ASC) VISIBLE,
  INDEX `fk_patient_in_diagnostics_center_diagnostics_center1_idx` (`diagnostics_center_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_patient_in_diagnostics_center_citizen1`
    FOREIGN KEY (`citizen_afm`)
    REFERENCES `mydb`.`citizen` (`afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_in_diagnostics_center_diagnostics_center1`
    FOREIGN KEY (`diagnostics_center_HIN`)
    REFERENCES `mydb`.`diagnostics_center` (`HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medical_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medical_check` (
  `test_result` VARCHAR(45) NOT NULL,
  `test_date` DATETIME NOT NULL,
  `patient_in_diagnostics_center_patient_history` INT NULL,
  `patient_in_diagnostics_center_citizen_afm` INT NULL,
  `patient_in_diagnostics_center_diagnostics_center_HIN` INT NULL,
  `patient_in_hospital_patient_history` INT NULL,
  `patient_in_hospital_citizen_afm` INT NULL,
  `patient_in_hospital_hospital_HIN` INT NULL,
  `test_test_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`test_result`, `test_date`, `patient_in_diagnostics_center_patient_history`, `patient_in_diagnostics_center_citizen_afm`, `patient_in_diagnostics_center_diagnostics_center_HIN`, `patient_in_hospital_patient_history`, `patient_in_hospital_citizen_afm`, `patient_in_hospital_hospital_HIN`, `test_test_type`),
  INDEX `fk_medical_check_patient_in_diagnostics_center1_idx` (`patient_in_diagnostics_center_patient_history` ASC, `patient_in_diagnostics_center_citizen_afm` ASC, `patient_in_diagnostics_center_diagnostics_center_HIN` ASC) VISIBLE,
  INDEX `fk_medical_check_patient_in_hospital1_idx` (`patient_in_hospital_patient_history` ASC, `patient_in_hospital_citizen_afm` ASC, `patient_in_hospital_hospital_HIN` ASC) VISIBLE,
  INDEX `fk_medical_check_test1_idx` (`test_test_type` ASC) VISIBLE,
  CONSTRAINT `fk_medical_check_patient_in_diagnostics_center1`
    FOREIGN KEY (`patient_in_diagnostics_center_patient_history` , `patient_in_diagnostics_center_citizen_afm` , `patient_in_diagnostics_center_diagnostics_center_HIN`)
    REFERENCES `mydb`.`patient_in_diagnostics_center` (`patient_history` , `citizen_afm` , `diagnostics_center_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_check_patient_in_hospital1`
    FOREIGN KEY (`patient_in_hospital_patient_history` , `patient_in_hospital_citizen_afm` , `patient_in_hospital_hospital_HIN`)
    REFERENCES `mydb`.`patient_in_hospital` (`patient_history` , `citizen_afm` , `hospital_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_check_test1`
    FOREIGN KEY (`test_test_type`)
    REFERENCES `mydb`.`test` (`test_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EODY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EODY` (
  `examination_code` INT NOT NULL,
  `medical_check_test_result` VARCHAR(45) NOT NULL,
  `medical_check_test_date` DATETIME NOT NULL,
  `medical_check_patient_in_diagnostics_center_patient_history` INT NULL,
  `medical_check_patient_in_diagnostics_center_citizen_afm` INT NULL,
  `medical_check_patient_in_diagnostics_center_diagnostics_center_HIN` INT NULL,
  `medical_check_patient_in_hospital_patient_history` INT NULL,
  `medical_check_patient_in_hospital_citizen_afm` INT NULL,
  `medical_check_patient_in_hospital_hospital_HIN` INT NULL,
  `medical_check_test_test_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`examination_code`),
  INDEX `fk_EODY_medical_check1_idx` (`medical_check_test_result` ASC, `medical_check_test_date` ASC, `medical_check_patient_in_diagnostics_center_patient_history` ASC, `medical_check_patient_in_diagnostics_center_citizen_afm` ASC, `medical_check_patient_in_diagnostics_center_diagnostics_center_HIN` ASC, `medical_check_patient_in_hospital_patient_history` ASC, `medical_check_patient_in_hospital_citizen_afm` ASC, `medical_check_patient_in_hospital_hospital_HIN` ASC, `medical_check_test_test_type` ASC) VISIBLE,
  CONSTRAINT `fk_EODY_medical_check1`
    FOREIGN KEY (`medical_check_test_result` , `medical_check_test_date` , `medical_check_patient_in_diagnostics_center_patient_history` , `medical_check_patient_in_diagnostics_center_citizen_afm` , `medical_check_patient_in_diagnostics_center_diagnostics_center_HIN` , `medical_check_patient_in_hospital_patient_history` , `medical_check_patient_in_hospital_citizen_afm` , `medical_check_patient_in_hospital_hospital_HIN` , `medical_check_test_test_type`)
    REFERENCES `mydb`.`medical_check` (`test_result` , `test_date` , `patient_in_diagnostics_center_patient_history` , `patient_in_diagnostics_center_citizen_afm` , `patient_in_diagnostics_center_diagnostics_center_HIN` , `patient_in_hospital_patient_history` , `patient_in_hospital_citizen_afm` , `patient_in_hospital_hospital_HIN` , `test_test_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`citizens_to_vaccinate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citizens_to_vaccinate` (
  `date_of_doses` DATETIME NOT NULL,
  `HDIKA_AMKA` INT NOT NULL,
  `vaccine_centers_hospital_HIN` INT NULL,
  `vaccine_centers_diagnostic_center_HIN` INT NULL,
  `date_to_vaccinate` DATETIME NOT NULL,
  PRIMARY KEY (`HDIKA_AMKA`),
  INDEX `fk_citizens_to_vaccinate_HDIKA1_idx` (`HDIKA_AMKA` ASC) VISIBLE,
  INDEX `fk_citizens_to_vaccinate_vaccine_centers1_idx` (`vaccine_centers_hospital_HIN` ASC, `vaccine_centers_diagnostic_center_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_citizens_to_vaccinate_HDIKA1`
    FOREIGN KEY (`HDIKA_AMKA`)
    REFERENCES `mydb`.`HDIKA` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_citizens_to_vaccinate_vaccine_centers1`
    FOREIGN KEY (`vaccine_centers_hospital_HIN` , `vaccine_centers_diagnostic_center_HIN`)
    REFERENCES `mydb`.`vaccine_centers` (`hospital_HIN` , `diagnostic_center_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`visit` (
  `date` DATETIME NOT NULL,
  `doctors_afm` INT NOT NULL,
  `patient_in_hospital_patient_history` INT NOT NULL,
  `patient_in_hospital_citizen_afm` INT NOT NULL,
  `patient_in_hospital_hospital_HIN` INT NOT NULL,
  PRIMARY KEY (`date`, `doctors_afm`, `patient_in_hospital_patient_history`, `patient_in_hospital_citizen_afm`, `patient_in_hospital_hospital_HIN`),
  INDEX `fk_visit_doctors1_idx` (`doctors_afm` ASC) VISIBLE,
  INDEX `fk_visit_patient_in_hospital1_idx` (`patient_in_hospital_patient_history` ASC, `patient_in_hospital_citizen_afm` ASC, `patient_in_hospital_hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_visit_doctors1`
    FOREIGN KEY (`doctors_afm`)
    REFERENCES `mydb`.`doctors` (`afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visit_patient_in_hospital1`
    FOREIGN KEY (`patient_in_hospital_patient_history` , `patient_in_hospital_citizen_afm` , `patient_in_hospital_hospital_HIN`)
    REFERENCES `mydb`.`patient_in_hospital` (`patient_history` , `citizen_afm` , `hospital_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_works_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor_works_in` (
  `ward_ward_id` VARCHAR(45) NOT NULL,
  `ward_hospital_HIN` INT NOT NULL,
  `doctors_afm` INT NOT NULL,
  `days` VARCHAR(45) NULL,
  PRIMARY KEY (`ward_ward_id`, `ward_hospital_HIN`, `doctors_afm`),
  INDEX `fk_ward_has_doctors_doctors1_idx` (`doctors_afm` ASC) VISIBLE,
  INDEX `fk_ward_has_doctors_ward1_idx` (`ward_ward_id` ASC, `ward_hospital_HIN` ASC) VISIBLE,
  CONSTRAINT `fk_ward_has_doctors_ward1`
    FOREIGN KEY (`ward_ward_id` , `ward_hospital_HIN`)
    REFERENCES `mydb`.`ward` (`ward_id` , `hospital_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ward_has_doctors_doctors1`
    FOREIGN KEY (`doctors_afm`)
    REFERENCES `mydb`.`doctors` (`afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examination` (
  `examination_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`examination_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitalization` (
  `symptoms` VARCHAR(45) NOT NULL,
  `treatment` VARCHAR(45) NOT NULL,
  `room_room_number` INT NOT NULL,
  `room_ward_ward_id` VARCHAR(45) NOT NULL,
  `room_ward_hospital_HIN` INT NOT NULL,
  `examination_result` VARCHAR(45) NULL,
  `examination_date` DATETIME NULL,
  `patient_in_hospital_patient_history` INT NOT NULL,
  `patient_in_hospital_citizen_afm` INT NOT NULL,
  `examination_examination_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`room_room_number`, `room_ward_ward_id`, `room_ward_hospital_HIN`, `patient_in_hospital_patient_history`, `patient_in_hospital_citizen_afm`),
  INDEX `fk_hospitalization_patient_in_hospital1_idx` (`patient_in_hospital_patient_history` ASC, `patient_in_hospital_citizen_afm` ASC) VISIBLE,
  INDEX `fk_hospitalization_examination1_idx` (`examination_examination_id` ASC) VISIBLE,
  CONSTRAINT `fk_hospitalization_room1`
    FOREIGN KEY (`room_room_number` , `room_ward_ward_id` , `room_ward_hospital_HIN`)
    REFERENCES `mydb`.`room` (`room_number` , `ward_ward_id` , `ward_hospital_HIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_patient_in_hospital1`
    FOREIGN KEY (`patient_in_hospital_patient_history` , `patient_in_hospital_citizen_afm`)
    REFERENCES `mydb`.`patient_in_hospital` (`patient_history` , `citizen_afm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_examination1`
    FOREIGN KEY (`examination_examination_id`)
    REFERENCES `mydb`.`examination` (`examination_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
